### ISSUE TITLE
Error with data examples

### ISSUE THREAD

**Issue by Seaizoe** [Damangir/Cascade#1]
Hi,
I have run Cascade.py with T1 and FLAIR data examples but there was a problem in the Task brainTissueSegmentation.
I have install Python 2.7.10 on a MAC OS X 10.10.3 (Yosemite).

The log file information:
 17:21:08 DEBUG  : /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python src/python/CascadeTTS.py --brain /Users/estela/Cascade_Out/image/T1/brain_mask.nii.gz --intermediate /Users/estela/Cascade_Out/image/T1/ --t1 /Users/estela/Cascade_Out/image/T1/T1.norm.nii.gz --flair /Users/estela/Cascade_Out/image/T1/FLAIR.norm.nii.gz --out /Users/estela/Cascade_Out/image/T1/brainTissueSegmentation.nii.gz
 17:21:09 DEBUG  : Traceback (most recent call last):

 17:21:09 DEBUG  :   File "src/python/CascadeTTS.py", line 68, in <module>

 17:21:09 DEBUG  :     with logger_mutex:

 17:21:09 DEBUG  : NameError: name 'logger_mutex' is not defined

 17:21:09 INFO   : 

 17:21:09 INFO   : The Cascade Academics pipeline. http://ki.se/en/nvs/cascade

 17:21:09 INFO   : Copyright (C) 2013-2014 Soheil Damangir - All Rights Reserved

 17:21:09 INFO   : 

 17:21:09 ERROR  : Error running /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python src/python/CascadeTTS.py --brain /Users/estela/Cascade_Out/image/T1/brain_mask.nii.gz --intermediate /Users/estela/Cascade_Out/image/T1/ --t1 /Users/estela/Cascade_Out/image/T1/T1.norm.nii.gz --flair /Users/estela/Cascade_Out/image/T1/FLAIR.norm.nii.gz --out /Users/estela/Cascade_Out/image/T1/brainTissueSegmentation.nii.gz

And the comand line output:
MBP-de-Estela:Cascade-master estela$ python src/python/Cascade.py -r /Users/estela/Cascade_Out -t data/test/t1.nii.gz -f data/test/flair.nii.gz 

The Cascade Academics pipeline. http://ki.se/en/nvs/cascade
Copyright (C) 2013-2014 Soheil Damangir - All Rights Reserved

Traceback (most recent call last):
  File "src/python/Cascade.py", line 741, in <module>
    ruffus.cmdline.run (options, pipeline_name = 'Cascade pipeline', logger=cascade.logger)
  File "/Applications/Cascade-master/src/python/ruffus/cmdline.py", line 687, in run
    **appropriate_options)
  File "/Applications/Cascade-master/src/python/ruffus/task.py", line 3727, in pipeline_run
    raise job_errors
ruffus.ruffus_exceptions.RethrownJobError: 

Original exception:

```
Exception #1
  'subprocess.CalledProcessError(Command '/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python' returned non-zero exit status 1)' raised in ...
   Task = def brainTissueSegmentation(...):
   Job  = [[brain_mask.nii.gz, T1.norm.nii.gz, FLAIR.norm.nii.gz] -> brainTissueSegmentation.nii.gz, {'brain': '/Users/estela/Cascade_Out/image/T1/brain_mask.nii.gz', 'intermediate': '/Users/estela/Cascade_Out/image/T1/', 't1': '/Users/estela/Cascade_Out/image/T1/T1.norm.nii.gz', 'flair': '/Users/estela/Cascade_Out/image/T1/FLAIR.norm.nii.gz', 'out': '/Users/estela/Cascade_Out/image/T1/brainTissueSegmentation.nii.gz'}]

Traceback (most recent call last):
  File "/Applications/Cascade-master/src/python/ruffus/task.py", line 685, in run_pooled_job_without_exceptions
    return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
  File "/Applications/Cascade-master/src/python/ruffus/task.py", line 507, in job_wrapper_io_files
    ret_val = user_defined_work_func(*param)
  File "src/python/Cascade.py", line 485, in brainTissueSegmentation
    cascade.binary_proxy.run(sys.executable, args)
  File "/Applications/Cascade-master/src/python/cascade/binary_proxy.py", line 112, in run
    output = check_output(cmd, args, output_files=output_files, silent=silent, just_print=just_print)
  File "/Applications/Cascade-master/src/python/cascade/binary_proxy.py", line 99, in check_output
    raise subprocess.CalledProcessError(retcode, cmd, out)
CalledProcessError: Command '/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python' returned non-zero exit status 1
```

Where is the problem? How can I solve it?
Thanks in advance
Estela

**Comment by Damangir** [comment]
Thanks Estela for the report. Cascade.py is depreciated and the current way to run the software is through script generators located at src/Shell. There is pre-generated scripts for use with FLAIR+T1+Freesurfer results, which is a typical pipeline people use, in the common directory.

Of course the documentation is outdated and needs to be updated. I try to prioritize updating the documentation and put some example runs.

**Comment by Damangir** [comment]
I've update the readme just now. I will elaborate more on how to run in different scenarios but I hope the current form is a good starting point. Feel free to inbox me though if you have any question.
